version: "2"
linters:
  enable:
  - asasalint
  - bidichk
  - bodyclose
  - durationcheck
  - errname
  - errorlint
  - copyloopvar
  - gocheckcompilerdirectives
  - importas
  - makezero
  - mirror
  - misspell
  - musttag
  - nilnil
  - revive
  - usetesting
  - thelper
  - tparallel
  - unconvert
  - wastedassign
  - zerologlint
  settings:
    revive:
      rules:
      - name: unused-parameter
        disabled: true
